name: Docker Build, Push Images

on:
  release:
    types: [published]
env:
  RELEASE: ${{ github.event.release.tag_name || 'latest' }}

jobs:
  build-dependant-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: hadoop-namenode
            path: ./namenode
            base_image: hadoop-pash-base

          - name: hadoop-datanode
            path: ./datanode
            base_image: hadoop-pash-base

          - name: hadoop-resourcemanager
            path: ./resourcemanager
            base_image: hadoop-pash-base

          - name: hadoop-nodemanager
            path: ./nodemanager
            base_image: hadoop-pash-base

          - name: hadoop-historyserver
            path: ./historyserver
            base_image: hadoop-pash-based

          - name: hadoop-submit
            path: ./submit
            base_image: hadoop-pash-base

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        run: |
          cd docker-hadoop

          # Build Image
          docker build -t binpash/${{ matrix.image.name }}:${{ env.RELEASE }} ${{ matrix.image.path }} \
          --build-arg RELEASE=${{ env.RELEASE }} --build-arg BASE=binpash/${{ matrix.image.base_image }}
          # Tag the image with 'latest'
          docker tag binpash/${{ matrix.image.name }}:${{ env.RELEASE }} binpash/${{ matrix.image.name }}:latest

